name: PR main - Lint, Build, Test
run-name: Lint, Build, Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2

      - name: Install Node.js v20.10
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '20.10'

      - name: Install Bun
        run: npm i -g bun && bun --version

      - name: Install dependencies
        run: bun i && cd templates/express-advanced && bun i

      - name: Lint
        run: bun lint

      - name: Build
        run: |
          bun run build && cd templates/express-advanced && bun run build
